spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proyecto_seguridad?useSSL=false
    username: root
    password: admin
  jpa:
#    show-sql: true # Que nos muestre el sql en pantalla (En el Log las diferentes Queries)
    hibernate:
      # Cuando arranquemos el servidor comprobar? si las Entidades corresponden con las tablas, sino las actualiza.
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9000
