spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proyecto_seguridad?useSSL=false
    username: root
    password: admin
    initialization-mode: never # DML Scripts Manuales
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9000

# Compilar 3 veces para cuando se tenga Servidor Linux y Windows Server:
# Arrancar con "ddl-auto: update" e "initialization-mode: never"
# Luego en "ddl-auto: none" e "initialization-mode: always" (Habrá error de Compílación)
# Finalmente "initization-mode: never" y "ddl-auto: none"